package com.example.hhfoundation.IPCMS.model

data class PatientX(
    val aadharnumber: String,
    val add_date: String,
    val address: String,
    val admissionnumber: String,
    val age: String,
    val birthdate: String,
    val bloodgroup: String,
    val district: String,
    val doctor: String,
    val education: String,
    val email: String,
    val f_name: String,
    val hospital_id: String,
    val how_added: Any,
    val id: String,
    val img_url: String,
    val ion_user_id: String,
    val m_name: String,
    val name: String,
    val nurse_id: String,
    val patient_id: String,
    val phone: String,
    val registration_time: String,
    val sch_phone: String,
    val schl: String,
    val schl_addr: String,
    val schl_dist: String,
    val schl_email: String,
    val section: String,
    val sex: String
)