package com.example.hhfoundation.IPCMS.model

data class SettingsXX(
    val address: String,
    val codec_purchase_code: Any,
    val codec_username: Any,
    val college: Any,
    val contact_boys: String,
    val contact_one: String,
    val contact_pref: String,
    val contact_tmrs: String,
    val currency: String,
    val discount: String,
    val district: String,
    val email: String,
    val facebook_id: Any,
    val hospital_id: String,
    val id: String,
    val invoice_logo: Any,
    val language: String,
    val latitute: String,
    val login_title: Any,
    val logo: Any,
    val longitude: String,
    val payment_gateway: Any,
    val phone: String,
    val principal: String,
    val school: String,
    val sms_gateway: Any,
    val strength: String,
    val system_vendor: String,
    val title: String,
    val vat: Any
)