package com.example.hhfoundation.labReport.model

data class Prescriptiondetail(
    val age: String,
    val bloodpressure: Any,
    val date: String,
    val department_name: String,
    val diagnote: String,
    val status_prd: String,
    val doctorreg_no: String,
    val doctrname: String,
    val follow_date: String,
    val follow_school: String,
    val gender: String,
    val follow: String,
    val added: String,
    val follow_reason: String,
    val labinves: Any,
    val note: String,
    val created_at: String,
    val health_issue: String,
    val patientid: String,
    val ref_status: String,
    val patient_reach: String,
    val presc: String,
    val appoitment_id: String,
    val discharge_count: Int,
    val lama_count: Int,
    val expired_count: Int,
    val patientname: String,
    val pid: String,
    val pulserate: Any,
    val refer_hospital: String,
    val spo2: Any,
    val sugar: Any,
    val temp: Any
)